#!/usr/bin/env bash
# Ubuntu container’s Nginx installation from listening on port 8
# configures nginx to run and listen to port 80

#remove the default in nginx

rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
